
name: test-action-alt

on:
  push:
  release:
    types: published

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2.2
      - name: use this action, with existing test results
        id: testAction1
        uses: ./
        with:
          coverage_results_path: jacoco-report/test.xml
          coverage_report_name: Code Coverage Report
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
