name: CI-TWO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jacoco-playground
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5.2.0
      with:
        java-version: 17
        distribution: 'corretto'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Coverage
      run: ./gradlew testCoverage

    - name: JaCoCo Code Coverage Report
      id: jacoco_reporter
      uses: ./
      with:
        coverage_results_path: ${{ github.workspace }}/jacoco-playground/build/reports/jacoco/testCoverage/testCoverage.xml
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: true
        minimum_coverage: 80
        fail_below_threshold: false
        publish_only_summary: false

    - name: Get the Coverage info
      run: |
        echo "Total coverage coverage-overall ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
        echo "coverage_percentage      : ${{ steps.jacoco_reporter.outputs.coverage_percentage }}"
        echo "coveragePercentageString : ${{ steps.jacoco_reporter.outputs.coveragePercentageString }}"
        echo "covered_lines            : ${{ steps.jacoco_reporter.outputs.covered_lines }}"
        echo "missed_lines             : ${{ steps.jacoco_reporter.outputs.missed_lines }}"
        echo "total_lines              : ${{ steps.jacoco_reporter.outputs.total_lines }}"
